### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by liteman** [carbonblack/cbapi-python#270]
**I am seeing this behaviour on: (please complete the following information):**
 - OS: Windows 10
 - Carbon Black Product: [e.g. CB Protection, CB Defense] Cloud / PSC
 - Python Version: 3.8

**Describe the bug**
I am unable to authenticate. The URI does _not_ include the org_key which is specified in .carbonblack/credentials.psc

**Steps to Reproduce**
My code
```
from cbapi.psc.defense import CbDefenseAPI  
from cbapi.psc.defense import Device  
  
c=CbDefenseAPI(profile="production")  
  
print(list(c.select(Device)))
```  

My credentials.psc
```
[default]  
url=https://defense-prod05.conferdeploy.net/  
token=<redacted>  
ssl_verify=False  
org_key=<redacted> 
```

**URI** == https://defense-prod05.conferdeploy.net/integrationServices/v3/device?limit=0 <--- no org_key

**Error**

> cbapi.errors.UnauthorizedError: Check your API Credentials: {"success": false, "message": "User is not authenticated"}

**Expected behavior**
Successful authentication and list of devices printed

**Comment by seanmcfeely** [comment]
I'm also experiencing this.

**Comment by avanbrunt-cb** [comment]
You should be using the new Device model which is imported from here instead `from cbapi.psc import Device`

The model you are using requires a legacy API type key instead of a Custom type key. This is likely the reason the authentication failed. If you switch the newer model the API request should work
