### ISSUE TITLE
[BUG] Device Update calls Invalid API

### ISSUE THREAD

**Issue by csanders-git** [carbonblack/cbapi-python#273]
**I am seeing this behaviour on: (please complete the following information):**
 - OS: All
 - Carbon Black Product: PSC
 - Python Version: 3.8

**Describe the bug**

Updating a Device model object with .save() calls a request with the PATCH method. This does not appear to be a supported API. Generally updating device specific parameters is not supported by CB (see https://developer.carbonblack.com/reference/carbon-black-cloud/platform/latest/devices-api/#update-policy for more details).

**Steps to Reproduce**

```
    cb = CbPSCBaseAPI()
    devices_query = cb.select(Device).where(<device_name>)
    device = devices_query.first()
    device.target_priority = "HIGH"
    device.save()
```

**Expected behavior**

Catches an empty update dict (https://github.com/carbonblack/cbapi-python/blob/04cd412e5d0938721b5adfa2003f18542c3899d7/src/cbapi/psc/defense/models.py#L56) and throws an error prior to making the API call indicating that the fields cannot be updated.

**Screenshots**

```
Sending HTTP PATCH /appservices/v6/orgs/{0}/devices/<REDACTED> with {}
HTTP PATCH /appservices/v6/orgs/{0}/devices/<REDACTED> took 24.623s (response 405)
Traceback (most recent call last):
  File "update_target_value.py", line 39, in <module>
    sys.exit(main())
  File "update_target_value.py", line 35, in main
    device.save()
  File "/env/lib/python3.8/site-packages/cbapi/models.py", line 464, in save
    self._update_object()
  File "/env/lib/python3.8/site-packages/cbapi/psc/models.py", line 33, in _update_object
    return self._patch_object()
  File "/env/lib/python3.8/site-packages/cbapi/psc/models.py", line 63, in _patch_object
    ret = self._cb.api_json_request(self.__class__._change_object_http_method,
  File "/env/lib/python3.8/site-packages/cbapi/connection.py", line 482, in api_json_request
    result = self.session.http_request(method, uri, headers=headers, data=raw_data, **kwargs)
  File "/env/lib/python3.8/site-packages/cbapi/connection.py", line 284, in http_request
    raise ClientError(error_code=r.status_code, message=r.text)
cbapi.errors.ClientError: Received error code 405 from API (No further information provided)
```

The generated request:

```
PATCH /appservices/v6/orgs/<REDACTED>/devices/<REDACTED> HTTP/1.1
Host: defense-prod05.conferdeploy.net
User-Agent: cbapi/1.7.2 Python/3.8.5
Accept-Encoding: gzip, deflate
Accept: */*
Connection: close
X-Auth-Token: <REDACTED>
Content-Type: application/json
{
}
```

**Comment by avanbrunt-cb** [comment]
@csanders-git The save function is not supported for the `cbapi.psc.device` model as our device model is not mutable. This functionality from the older `cbapi.psc.defense.device` has moved to a device action specifically policy update as this was the only supported properties for the patch request.

Since we are moving to the `cbc sdk` for the Carbon Black Cloud product, I have verified the bug did not transfer instead the following error is thrown for the `cbc_sdk.platform.device`
```
>>> device.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/avanbrunt/reno/Work/carbon-black-cloud-sdk-python/src/cbc_sdk/base.py", line 257, in __getattr__
    raise AttributeError("'{0}' object has no attribute '{1}'".format(self.__class__.__name__,
AttributeError: 'Device' object has no attribute 'save'
```

Here is a link to our recently released alpha release for the [cbc sdk](https://github.com/carbonblack/carbon-black-cloud-sdk-python). The alpha release is an full parity to cbapi for the carbon black cloud product. We are finishing up some final items before we make a GA release

**Comment by avanbrunt-cb** [comment]
Closing as resolved
