### ISSUE TITLE
Add .webui_link to Query objects

### ISSUE THREAD

**Issue by jgarman** [carbonblack/cbapi-python#76]
Look into adding a .webui_link attribute to Query objects, so users can construct a Query and be redirected into the Cb Response console

**Comment by jgarman** [comment]
I've added a webui_link attribute to cbapi.response.query.Query objects. Note that since I don't include a "minimum" or "maximum" time on the query, it uses the default in the UI (which is 3 days). You can of course adjust that by selecting a different time period, but this may mean you get "different" results depending on the UI (defaults to 3 days) and the API (defaults to all time). Thoughts?

**Comment by jjfallete** [comment]
@jgarman I see all time as being more useful, at least for my use cases.

Can you remind me on how one would set the time of the query to be all time instead of the 3 day default?

Let's assume we have something like:
`processes = (c.select(Process).where('hostname:MyHostPC').group_by("id"))
urlToUI = processes.webui_link`

**Comment by avanbrunt-cb** [comment]
Closing due to outdated status. Please reopen if still a concern
